FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libssl3 zlib1g libffi8 libsqlite3-0 libbz2-1.0 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=cpython-builder:latest /cpython /cpython
WORKDIR /cpython
